class RecommendationsController < ApplicationController

    def stores
        $n_stores = params[:n_stores] 
        redirect_to recommendations_path
    end
    

    def show
        session_id = session[:current_user_id]

        # check if there is already an entry in Recommendations for the current user
        # if not, then we will save the recommendations generated by search_v3.py to Recommendations table
        if (Recommendation.find_by(list_id: session_id).blank?)
            require 'json'
            list_objects = List.where(list_id: session_id)
            list = List.list_as_array(list_objects)
            quantities = List.item_quantities_as_array(list_objects)
            n_stores = $n_stores

            result = `python3 -W ignore #{ENV["PWD"] + "/backend/search_v3.py"} '#{list}' #{n_stores}` # pass l as an argument 
            print result
            hash = JSON.parse(result, { allow_nan: true }) # turn string result into a hash
            $stores = [hash['1']['store'], hash['2']['store'], hash['3']['store']]

            store = ""
            subtotal = ""
            results = ""
            hash.each do |rank, rec_data|
                rec_data.each do |key, value|
                    if (key == "store")
                        store = value
                    elsif (key == "subtotal")
                        subtotal = value
                    else
                        results = value
                    end
                end
                results.each do |key, value|
                    if (key == "price")
                        prices = value
                        i = 0
                        for x in quantities
                            if (x > 1) # if the quantity of an item is > 1
                                item_price = prices[i] # grab the per unit price
                                additional_item_price = item_price * (x-1) # multiply by x-1. if x = 2, additional_item_price is the same as item_price
                                subtotal += additional_item_price # tack on the additional_item_price to subtotal
                            end
                            i += 1
                        end
                    end
                end
                Recommendation.create(list_id: session_id, rec_num:rank, store:store, subtotal:subtotal, rec:results)
            end

        # if there is an entry in Recommendations for the current user,
        # then we will query for it in Recommendations table and simply show these   
        else
            first_rec = Recommendation.find_by(list_id: session_id, rec_num: 1)
            second_rec = Recommendation.find_by(list_id: session_id, rec_num: 2)
            third_rec = Recommendation.find_by(list_id: session_id, rec_num: 3)

            $stores = [first_rec.store, second_rec.store, third_rec.store]
        end
    end

    def number
        session_id = session[:current_user_id]
        list_objects = List.where(list_id: session_id)
        $quantities = List.item_quantities_as_array(list_objects)
        rec_num = params[:rec_num]
        $current_recommendation = Recommendation.find_by(list_id: session_id, rec_num: params[:id])
        $list = []
        $products = []
        $prices = []
        $is_sale = []
        $stores = []
        $current_recommendation.rec.each do |key, value|
            if (key == "full_product_text")
                $products = value
            elsif (key == "price")
                $prices = value
            elsif (key == "is_sale")
                $is_sale = value
            elsif (key == "list_item")
                $list = value
            elsif (key == "store")
                $stores = value
            end
        end
    end
end